#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          rsl,           tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     LeftFront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     LeftBack,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C2_1,     RightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     RightBack,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C4_1,     Lift,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C4_2,     Spinner,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C3_1,    BucketRight,          tServoStandard)
#pragma config(Servo,  srvo_S4_C3_2,    PTO,                  tServoStandard)
#pragma config(Servo,  srvo_S4_C3_3,    BucketLeft,           tServoStandard)
#pragma config(Servo,  srvo_S4_C3_4,    Turntable,            tServoStandard)
#pragma config(Servo,  srvo_S4_C3_5,    Ratchet,              tServoStandard)
#pragma config(Servo,  srvo_S4_C3_6,    Flipper,              tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BUCKET_LEFT_SERVO
#define BUCKET_RIGHT_SERVO
#define LIFT_MOTOR
#define FLAG_MOTOR
#define FLAG_SERVO
#define DRIVETRAIN_LEFT_FRONT
#define DRIVETRAIN_LEFT_BACK
#define DRIVETRAIN_RIGHT_FRONT
#define DRIVETRAIN_RIGHT_BACK
