#pragma systemFile

#define BUCKET_LEFT_SERVO
#define BUCKET_RIGHT_SERVO
#define LIFT_MOTOR
#define FLAG_MOTOR
#define FLAG_SERVO
#define DRIVETRAIN_LEFT_FRONT
#define DRIVETRAIN_LEFT_BACK
#define DRIVETRAIN_RIGHT_FRONT
#define DRIVETRAIN_RIGHT_BACK
