#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          rsl,           tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     LeftFront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     LeftBack,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C2_1,     RightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     RightBack,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C3_1,     Lift,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S4_C3_2,     Spinner,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C4_1,    BucketRight,          tServoStandard)
#pragma config(Servo,  srvo_S4_C4_2,    PTO,                  tServoStandard)
#pragma config(Servo,  srvo_S4_C4_3,    BucketLeft,           tServoStandard)
#pragma config(Servo,  srvo_S4_C4_4,    Turntable,            tServoStandard)
#pragma config(Servo,  srvo_S4_C4_5,    Ratchet,              tServoStandard)
#pragma config(Servo,  srvo_S4_C4_6,    Flipper,              tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Controller.c"
#include "GeminiDrivetrain.c"
#include "GeminiLift.c"

void initializeRobot()
{
  bFloatDuringInactiveMotorPWM = false;
  return;
}


task main()
{
  initializeRobot();
  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
    updateControllers();

    calculateDrive(joystick.joy1_x1, joystick.joy1_y1);

    if (ControllerButtonDown(BUTTON_X, CONTROLLER_1)) {
      liftBottomPositionSafety();
    } else if (ControllerButtonDown(BUTTON_Y, CONTROLLER_1)) {
      liftDumpPositionSafety();
    } else if (ControllerButtonDown(BUTTON_RSTICK, CONTROLLER_1)) {
      liftHangPositionSafety();
    } else {
      liftUpSpeed(joystick.joy1_y2);
    }

    if (ControllerButtonPressed(BUTTON_LB, CONTROLLER_1)) {
      setDrivePower(30);
    } else if (ControllerButtonReleased(BUTTON_LB, CONTROLLER_1)) {
      setDrivePower(100);
    }

    if (ControllerButtonDown(BUTTON_LSTICK, CONTROLLER_1)) {
      PlayImmediateTone(4186, 1);
    }

  }
}
